version: '3.8'
services:
  db:
    image: postgres:15
    container_name: store_postgres
    restart: always
    environment:
      POSTGRES_USER: store_user
      POSTGRES_PASSWORD: store_password
      POSTGRES_DB: store_db
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: store_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: adminIoana@dynamicStore.com
      PGADMIN_DEFAULT_PASSWORD: adminIoana
    ports:
      - '5050:80'
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  db_data:
  pgadmin_data:
